addSbtPlugin("org.scala-js"     % "sbt-scalajs"    % "1.16.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"    % "0.6.3")
addSbtPlugin("com.geirsson"     % "sbt-ci-release" % "1.5.7")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"   % "0.10.1")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"   % "2.4.6")
