addSbtPlugin("org.scala-js"     % "sbt-scalajs"    % "1.6.0")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"    % "0.5.3")
addSbtPlugin("com.geirsson"     % "sbt-ci-release" % "1.5.7")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"   % "0.9.29")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"   % "2.4.2")
